### PR TITLE
Resolve #161.

### LINKED ISSUE #161: Refactor deleteTunnel() to return the actual response and add unit tests
## Description

Currently deleteTunnel() does not handle or returns the response from the server. Basically not telling the user why a call to delete a tunnel has failed.

## Motivation and Context

It is implemented differently compared to most other requests. It lacks unit tests as it is not testable with no response returned. If it fails no useful info to the user.

### PR DESCRIPTION
**Pull request by sceiler**
## Description

This resolves #161.

## Motivation and Context

This resolves #161.

## How Has This Been Tested?

Unit tests and E2E test.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (change which improves current code base; please describe the change)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/saucelabs/saucerest-java/blob/master/CONTRUBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] All new and existing tests passed locally
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: src/main/java/com/saucelabs/saucerest/SauceREST.java [hunk 1]
```diff
@@ -1228,6 +1231,14 @@ private HttpURLConnection setConnection(String jobId, URL restEndpoint) throws I
         return connection;
     }
 
+    private HttpURLConnection setConnection(String jobId, URL restEndpoint) throws IOException {
+        return setConnection(jobId, restEndpoint, "GET");
```
Comment (diemol) [inline src/main/java/com/saucelabs/saucerest/SauceREST.java:1235]: Not relevant right now, but as a future improvement, I would find a way to avoid passing HTTP methods as Strings. Probably there is some `ENUM` somewhere that helps us to pass them in a strong typed way.

File: .github/workflows/codeql-analysis.yml [hunk 2]
```diff
@@ -1,8 +1,8 @@
 name: "Code Scanning - Action"
 
 on:
-  push:
-  pull_request:
+  push: [master, 1.1.0_master, 1.1.0_dev]
```
Comment (diemol) [inline .github/workflows/codeql-analysis.yml:4]: No need to change this, but just wondering why this is needed?

**Review by diemol — APPROVED** [review]
Thank you, @sceiler!

File: src/main/java/com/saucelabs/saucerest/SauceREST.java (hunk 1 above)
Comment (sceiler) [reply src/main/java/com/saucelabs/saucerest/SauceREST.java:1235]: Good point! Thanks, I have created #172 to change this. I think Java has it somewhere defined and if not I will just create my own HTTP method enum.

File: .github/workflows/codeql-analysis.yml (hunk 2 above)
Comment (sceiler) [reply .github/workflows/codeql-analysis.yml]: Thanks for the hint. Forgot to backmerge but this has the wrong syntax. I created a 1.1.0 version branch and project for this. I would like to do a couple of refactoring and they would most likely not be compatible with older versions. A user would have to change some code before using 1.1.0 so I wanted to have it completely separate to avoid issues short-term.
